### ISSUE TITLE
Indentation of SQL statement seems broken

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#33]
The instruction to **Fix columns with ENUM data types** seems to be mis-indented:

```
➤ Adjust your database schema
Run the following SQL statements against your database:

  Fix columns with ENUM data types
  https://pris.ly/d/schema-incompatibilities#enums-are-represented-as-text-in-database

    CREATE TYPE "dr4$dev"."Role" AS ENUM ('ADMIN', 'CUSTOMER');
ALTER TABLE "dr4$dev"."User" ALTER COLUMN "role" SET DATA TYPE "dr4$dev"."Role" using "role"::"dr4$dev"."Role";
```

I think the right indentation would be:

```
➤ Adjust your database schema
Run the following SQL statements against your database:

  Fix columns with ENUM data types
  https://pris.ly/d/schema-incompatibilities#enums-are-represented-as-text-in-database

    CREATE TYPE "dr4$dev"."Role" AS ENUM ('ADMIN', 'CUSTOMER');
    ALTER TABLE "dr4$dev"."User" ALTER COLUMN "role" SET DATA TYPE "dr4$dev"."Role" using "role"::"dr4$dev"."Role";
```

or even

```
➤ Adjust your database schema
Run the following SQL statements against your database:

  Fix columns with ENUM data types
  https://pris.ly/d/schema-incompatibilities#enums-are-represented-as-text-in-database

    CREATE TYPE "dr4$dev"."Role" AS ENUM ('ADMIN', 'CUSTOMER');
      ALTER TABLE "dr4$dev"."User" ALTER COLUMN "role" SET DATA TYPE "dr4$dev"."Role" using "role"::"dr4$dev"."Role";
```

**Comment by matthewmueller** [comment]
This should be fixed now

**Comment by nikolasburk** [comment]
Just tried it but the indentation is still broken for me 🤔

**Comment by matthewmueller** [comment]
Maybe your terminal was too small? Here's what it looks like to me:

<img width="1010" alt="CleanShot 2020-07-03 at 18 46 17@2x" src="https://user-images.githubusercontent.com/170299/86487168-b1c04f00-bd5d-11ea-9002-65003cd908f6.png">
<img width="1000" alt="CleanShot 2020-07-03 at 18 46 06@2x" src="https://user-images.githubusercontent.com/170299/86487171-b2f17c00-bd5d-11ea-89e1-b29368fef020.png">

**Comment by nikolasburk** [comment]
Still have the same issue with a wider terminal: 

![image](https://user-images.githubusercontent.com/4058327/86607618-c7c24f80-bfa9-11ea-89db-ff9f7be12f83.png)

It also seems like get a different output altogether, I was using this Prisma 1 datamodel:

```graphql
type User {
  id: ID! @id
  email: String @unique
  name: String!
  posts: [Post!]!
  role: Role! @default(value: CUSTOMER)
  profile: Profile
  jsonData: Json 
}

type Post {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  title: String!
  content: String
  published: Boolean! @default(value: false)
  author: User @relation(link: TABLE)
  categories: [Category!]!
}

type Profile {
  id: ID! @id
  bio: String
  user: User! @relation(link: INLINE)
}

type Category {
  id: ID! @id
  name: String!
  posts: [Post!]!
}

enum Role {
  ADMIN
  CUSTOMER
}
```

And this Prisma 2 schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Category {
  id   String @default(cuid()) @id
  name String
  Post Post[] @relation(references: [id])
}

model Post {
  content   String?
  createdAt DateTime
  id        String     @default(cuid()) @id
  published Boolean
  title     String
  updatedAt DateTime
  Category  Category[] @relation(references: [id])
  User      User[]     @relation(references: [id])
}

model Profile {
  bio  String?
  id   String  @default(cuid()) @id
  user String?
  User User?   @relation(fields: [user], references: [id])
}

model User {
  email    String?   @unique
  id       String    @default(cuid()) @id
  jsonData String?
  name     String
  role     String
  Profile  Profile[]
  Post     Post[]    @relation(references: [id])
}
```

**Comment by matthewmueller** [comment]
This should be fixed in `0.0.29`
